repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: no-commit-to-branch
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: check-env-file-in-gitignore
        name: check_env_file_in_gitignore
        description: Check that .env file is ignored in .gitignore
        language: system
        entry: bash -c 'if grep -Fxq ".env" .gitignore; then exit 0; else exit 1; fi'

      - id: check-datetime-now
        name: check_datetime_now
        description: Prefer datetime.now(tz=timezone.utc) over datetime.now and datetime.utcnow
        language: pygrep
        entry: 'datetime\.now\(\)\s+datetime\.utcnow\(\)'
        types: [ python ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
          - --keep-runtime-typing

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
        description: Check that all mock methods are called

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        description: 'Mypy is an optional static type checker for Python'
        pass_filenames: false
        additional_dependencies:
          - "pydantic>=2.0.0,<3.0.0"
          - "types-cachetools"
          - "types-aiofiles"
          - "types-requests"
          - "types-deprecated"
        name: mypy-src
        files: ^src/
        entry: mypy --config-file pyproject.toml -p src

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit
        description: Bandit is a tool for finding common security issues in Python code
        entry: bandit -c pyproject.toml -q
        additional_dependencies: [ ".[toml]" ]
